export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const GET_TOPTHREE_REQUEST = "GET_TOPTHREE_REQUEST";
export const GET_TOPTHREE_SUCCESS = "GET_TOPTHREE_SUCCESS";
export const GET_TOPTHREE_FAILED = "GET_TOPTHREE_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";
export const ADD_PRODUCT_TO_WISHLIST_SUCCESS =
  "ADD_PRODUCT_TO_WISHLIST_SUCCESS";
export const ADD_PRODUCT_TO_WISHLIST_REQUEST =
  "ADD_PRODUCT_TO_WISHLIST_REQUEST";
export const ADD_PRODUCT_TO_WISHLIST_FAILED = "ADD_PRODUCT_TO_WISHLIST_FAILED";
export const ADD_PRODUCT_TO_CART_SUCCESS =
  "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_REQUEST =
  "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_FAILED = "ADD_PRODUCT_TO_CART_FAILED";
export const REMOVE_PRODUCT_FROM_CART_FAILED = "REMOVE_PRODUCT_FROM_CART_FAILED";
export const REMOVE_PRODUCT_FROM_CART_SUCCESS =
  "REMOVE_PRODUCT_FROM_CART_SUCCESS";
export const REMOVE_PRODUCT_FROM_CART_REQUEST =
  "REMOVE_PRODUCT_FROM_CART_REQUEST";
